### ISSUE TITLE
sortable pill checkbox doesnot update visually on customizer

### ISSUE THREAD

**Issue by sauravxtha** [maddisondesigns/customizer-custom-controls#15]
sotable pill check box doesnot update visually on customizer. i mean ordering of checkbox doses not update on customizer settings

**Comment by maddisondesigns** [comment]
I just had another look at this. The control is saving the data back to the database in the correct re-ordered state. When I'm loading the data into the control though, I'm using the original order, rather than the saved order, which is the issue.

Thanks for picking that up. I'll get that sorted and will let you know when it's fixed.

**Comment by maddisondesigns** [comment]
This has been fixed.

You can just grab a new copy of `inc/custom-controls.php`.
