### ISSUE TITLE
Error Uncaught TypeError: $(...).sortable is not a function

### ISSUE THREAD

**Issue by ASL07** [maddisondesigns/customizer-custom-controls#22]
Hi, 
Thanks for the repo, looks great.
I am testing your controls with my theme based on Sage 9 and I am getting the next error:
`
Uncaught TypeError: $(...).sortable is not a function
`
on customizer.js
```
$( ".pill_checkbox_control .sortable" ).sortable({
		placeholder: "pill-ui-state-highlight",
		update: function( event, ui ) {
			skyrocketGetAllPillCheckboxes($(this).parent());
		}
	});
```

Any idea what the problem is? 
Thanks

**Comment by maddisondesigns** [comment]
jQuery `sortable` requires [jQuery UI](https://jqueryui.com/sortable/).

It looks like I didn't specify that as a dependency when enqueuing the scripts for that Pill Checkbox Control. I have it set on another couple of controls (Sortable Repeater and Slider controls) which is why I never picked it up. I'm guessing you're not using those other controls though, which is why it didn't get enqueued. I've just fixed this up for you now.

You can just grab a new copy of `inc/custom-controls.php` and that should fix it for you.

**Comment by ASL07** [comment]
Great! Working now 
Thank you

**Comment by maddisondesigns** [comment]
No worries. Great to hear! 👍
