### ISSUE TITLE
Enqueuing Google Fonts

### ISSUE THREAD

**Issue by paolosax** [maddisondesigns/customizer-custom-controls#26]
Hello, I'm testing your nice Google Fonts selector customizer control. 
It works great for the pure selection of the fonts data, but my question is: once implemented, this should automatically enqueue the link to the actual font (in order to be rendered in the page) or I have to enqueue separately the font through the google CDN? 'Cause now the fonts are not rendered.
Maybe/surely I've missed something... 

Thank you in advance
Paolo

**Comment by maddisondesigns** [comment]
Hi Paolo,

These are simply custom controls for the customizer, how you use them in your theme is up to you.

In the case of the Font control, you're correct, you will need to load that font within your theme otherwise your styles wont work properly.

The good news though, is that I've provided an example of how to do this, in my sample theme. There's a link to the sample theme in the readme file.

In particular, have a look at the [twentytwelve_get_font_url()](https://github.com/maddisondesigns/Customizer-Custom-Controls-Sample-Theme/blob/d802f99617e5380989d7e7e5b3930467a5f58436/customcontrols/functions.php#L91) function, where I load the actual font that was selected in the Customizer, and also take a look at the [skyrocket_customizer_css_styles()](https://github.com/maddisondesigns/Customizer-Custom-Controls-Sample-Theme/blob/d802f99617e5380989d7e7e5b3930467a5f58436/customcontrols/functions.php#L851) function that outputs the necessary css for using our selected font.

I hope this helps.

**Comment by paolosax** [comment]
Hello Anthony, thanks for your quick reply.
Helps a lot indeed! (_"...remember Paolo: always read the ReadMe"_) :)
...it's just that at first I thought that the control was standalone also concerning the fonts url aspect.
Good job and thanks fo the support!

**Comment by maddisondesigns** [comment]
No worries Paolo. Glad I was able to help 🙂
