### ISSUE TITLE
Slider control doesn't work if "step" is less than 1

### ISSUE THREAD

**Issue by idlevibes95** [maddisondesigns/customizer-custom-controls#27]
Hi! Thank you for the useful controls!

I'm trying to use the Slider control for a font size control. The `skyrocket_sanitize_integer` sanitization only works if step is 1 (doesn't work if it's .1 or .5). But if I use the `fawn_theme_range_sanitization` sanitization the control stops working entirely (I can move the slider in the customizer, but the font size doesn't change at all). I've copied all the CSS, scripts + controls. I uploaded the sample theme you've provided to a test blog and it works correctly there. I've gone over all the codes several times, but I can't find the mistake.

**Comment by maddisondesigns** [comment]
Hi @idlevibes95,

It's most likely because you're using `skyrocket_sanitize_integer`. You should be using `skyrocket_range_sanitization` instead.

Here's a short screencast I made for you showing the Slider Control using a step of 0.5.
https://share.getcloudapp.com/geuANqNL

I'm not sure if you saw in the Read Me, but I have a [Customizer Custom Controls Sample Theme](https://github.com/maddisondesigns/Customizer-Custom-Controls-Sample-Theme) that shows all these controls in action, and shows examples of their use.

I hope that helps.

**Comment by idlevibes95** [comment]
I tried adding it again and everything works perfectly now. Thank you!

**Comment by maddisondesigns** [comment]
Great to hear! 👍
