### ISSUE TITLE
How do I load it into my plug-in

### ISSUE THREAD

**Issue by muze-page** [maddisondesigns/customizer-custom-controls#28]
Sorry, my technology is limited. After I failed several times, I came here to ask for help

**Comment by maddisondesigns** [comment]
Take a look at how my [Sample Theme](https://github.com/maddisondesigns/Customizer-Custom-Controls-Sample-Theme) loads everything. Adding it into a plugin should be very similar to that.

**Comment by maddisondesigns** [comment]
I created a very simple sample plugin for you to look at, so you can see how to implement my Customizer Controls within a plugin (rather than a theme). As mentioned above, it's very similar to how you implement it within a theme.

You can find the sample plugin in my [Customizer-Custom-Controls-Sample-Plugin](https://github.com/maddisondesigns/Customizer-Custom-Controls-Sample-Plugin) repo.

Simply upload the 'simple-custom-controls' folder to your '/wp-content/plugins/' directory and activate. Read the readme.txt file in the 'simple-custom-controls' plugin folder to find out what controls this sample plugin adds to the Customizer.

**Comment by maddisondesigns** [comment]
I presume the details I posted above help with your query so I'm going to close this for now.
