### ISSUE TITLE
Multi Select Dropdown don't removing last value when clearing the list

### ISSUE THREAD

**Issue by ghost** [maddisondesigns/customizer-custom-controls#4]
What happens:
When removing all choices from multi-select dropdown list 
customizer should save empty value for correct theme_mod
Instead, after re-opening customizer i still have one selected value left in select-dropdown list
I can't wipe out all choices from select dropdown , also echoing theme_mode returns that one value
When removing last value from list i can't Publish this change - its like nothing happens inside Customizer,so i need change something else to click on Publish.

**Comment by ghost** [comment]
What do you think about quick and dirty solution for this?
Not created or tested yet:
Outside the foreach loop, in your php class we can create  single hidden,always selected 
label with empty value, so users can select/deselect all visible labels, and this one without any value should be treated as this one broken thing that is saved, no harm is done since value of it will be empty, of course sanitization should allow empty values(?)
Can think right now how to fix this in proper way

**Comment by ghost** [comment]
Another little problem:
 When you have fresh-opened Customizer, and you unselect one value from list,
then selecting this value again wont trigger change on Publish button.
So you can't toggle the same option to be checked/unchecked 
 before you slect/unselect something else.

**Comment by maddisondesigns** [comment]
I'm still no closer to sorting this issue out, unfortunately, and I've spent hours working on it. I still haven't worked out why that last item isn't triggering a change and even when I try to trigger a change on every unselect, the Publish button still doesn't activate like it should.

I'm not sure that second issue you mentioned, is actually an issue. If I have two items saved in the database and then go into the customizer, the Select2 shows those two items as selected (ie. defaults). As soon as I unselect one item, the change is triggered and the Publish button becomes active. Even if I reselect that one I just deselected, the Publish button remains active.

The only issue appears to be when there's one selected item. Unselecting that item doesn't seem to trigger a change for some reason, and I have no idea why as yet.

**Comment by maddisondesigns** [comment]
This has been fixed! 🎉

The Select2 still seems to have an issue with triggering the change when the items are cleared, as does triggering the change manually, so I changed the way the control works to get around the issue. I'm using a hidden field, like I have with several of my other controls. This field will get updated with the Selects value every time it gets changed.

A couple of things that I wanted to make you aware of when using this new code:
- The control now provides a 'clear all' icon which allows you to clear the field.
- A limitation with Select2 is that if you use this 'clear all' option, you also have to specify a placeholder. The default placeholder I've specified is 'Please select...'. You can override this string using the `placeholder` paramater in the `input_attrs` (see updated example code in readme).
- The setting saved to the database will always be a string. If you are using the multiselect dropdown (i.e. 'multiselect' => true) and you've selected multiple entries, they will be saved to the database as a series of comma delimited strings.
- To santize your controls data, use my `skyrocket_text_sanitization` function for both the single select and the multiselect.

Just be aware, the first time you use this control after updating your code, it may appear to be not working. This is going to be due to the way the old data was saved and how it's now saved. When using the multiselect option previously, it saved the data as an array of strings, whereas now it doesn't, so when you first go into the customizer it wont pick up your old (multiselect) values.

I would recommend either clearing the options from your database manually, or better yet, just clear your Select2 Dropdown field and save. Then exit the customizer and go back in and reset the options for that control.

I've given it a lot of testing, including the clearing of a single entry in a multiselect and everything seems to be working fine.

**Comment by ghost** [comment]
Thank you for your hard work, i will use it and abuse it...just joking, if i found anything good/bad/worth of changing i will raport back here
